# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecard',
            fields=[
                ('ecard_key', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('wechat_key', models.CharField(max_length=100)),
            ],
        ),
    ]
